import React, { useState } from 'react';

/**
 * SummaryDisplay Component
 * Shows section-by-section summaries in expandable cards
 */
function SummaryDisplay({ summaries }) {
  const [expandedSections, setExpandedSections] = useState({});

  const toggleSection = (section) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const sectionIcons = {
    'Abstract': '📄',
    'Introduction': '🚀',
    'Methods': '🔬',
    'Results': '📊',
    'Conclusion': '🎯'
  };

  return (
    <div className="space-y-4">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Section Summaries</h2>
        <p className="text-sm text-gray-600">
          AI-generated comprehensive summaries with key findings, statistics, and details from each section
        </p>
      </div>

      {Object.entries(summaries).map(([section, summary]) => {
        const isExpanded = expandedSections[section];
        const isAvailable = summary && summary !== "Section not available in paper" && summary !== "Not Found";

        return (
          <div
            key={section}
            className={`border rounded-lg overflow-hidden transition-all duration-200 ${
              isAvailable 
                ? 'border-gray-300 hover:border-blue-400 hover:shadow-md' 
                : 'border-gray-200 bg-gray-50'
            }`}
          >
            <button
              onClick={() => isAvailable && toggleSection(section)}
              className="w-full px-6 py-4 flex items-center justify-between bg-white hover:bg-gray-50 transition-colors duration-150"
              disabled={!isAvailable}
            >
              <div className="flex items-center space-x-3">
                <span className="text-2xl">{sectionIcons[section] || '📖'}</span>
                <div className="text-left">
                  <h3 className="font-semibold text-gray-900">{section}</h3>
                  {!isAvailable && (
                    <p className="text-xs text-gray-500 mt-0.5">Section not found in paper</p>
                  )}
                </div>
              </div>
              
              {isAvailable && (
                <svg
                  className={`w-5 h-5 text-gray-500 transition-transform duration-200 ${
                    isExpanded ? 'transform rotate-180' : ''
                  }`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              )}
            </button>

            {isExpanded && isAvailable && (
              <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                <p className="text-gray-700 leading-relaxed">{summary}</p>
              </div>
            )}
          </div>
        );
      })}

      {/* Summary Statistics */}
      <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span className="text-sm font-medium text-blue-900">
              {Object.values(summaries).filter(s => s && s !== "Section not available in paper" && s !== "Not Found").length} sections summarized
            </span>
          </div>
          <span className="text-xs text-blue-700">
            Generated by Agent 2
          </span>
        </div>
      </div>
    </div>
  );
}

export default SummaryDisplay;

